#!/bin/sh -e
# automatically generated by :robrank/tools/many.sh

tq r5 -- python3 train.py -C fashion:c2f1:pcontrastN
tq r5 -- python3 train.py -C fashion:c2f1:ptripletN
tq r5 -- python3 train.py -C fashion:c2f1:pmtripletN
tq r5 -- python3 train.py -C fashion:c2f1:pstripletN
tq r5 -- python3 train.py -C fashion:c2f1:pdtripletN
tq r5 -- python3 train.py -C fashion:c2f1:pgliftE
tq r5 -- python3 train.py -C fashion:c2f1:pnpairE
tq r5 -- python3 train.py -C fashion:c2f1:pmarginN
tq r5 -- python3 train.py -C fashion:c2f1:pquadN
tq r5 -- python3 train.py -C fashion:c2f1:pmsC
tq r5 -- python3 train.py -C fashion:c2f1:prhomN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-pcontrastN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-ptripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-pmtripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-pstripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-pdtripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-pgliftE
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-pnpairE
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-pmarginN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-pquadN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-pmsC
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1-prhomN

tq r5 -- python3 train.py -C fashion:c2f1d:pcontrastN
tq r5 -- python3 train.py -C fashion:c2f1d:ptripletN
tq r5 -- python3 train.py -C fashion:c2f1d:pmtripletN
tq r5 -- python3 train.py -C fashion:c2f1d:pstripletN
tq r5 -- python3 train.py -C fashion:c2f1d:pdtripletN
tq r5 -- python3 train.py -C fashion:c2f1d:pgliftE
tq r5 -- python3 train.py -C fashion:c2f1d:pnpairE
tq r5 -- python3 train.py -C fashion:c2f1d:pmarginN
tq r5 -- python3 train.py -C fashion:c2f1d:pquadN
tq r5 -- python3 train.py -C fashion:c2f1d:pmsC
tq r5 -- python3 train.py -C fashion:c2f1d:prhomN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-pcontrastN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-ptripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-pmtripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-pstripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-pdtripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-pgliftE
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-pnpairE
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-pmarginN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-pquadN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-pmsC
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1d-prhomN

tq r5 -- python3 train.py -C fashion:c2f1e:pcontrastN
tq r5 -- python3 train.py -C fashion:c2f1e:ptripletN
tq r5 -- python3 train.py -C fashion:c2f1e:pmtripletN
tq r5 -- python3 train.py -C fashion:c2f1e:pstripletN
tq r5 -- python3 train.py -C fashion:c2f1e:pdtripletN
tq r5 -- python3 train.py -C fashion:c2f1e:pgliftE
tq r5 -- python3 train.py -C fashion:c2f1e:pnpairE
tq r5 -- python3 train.py -C fashion:c2f1e:pmarginN
tq r5 -- python3 train.py -C fashion:c2f1e:pquadN
tq r5 -- python3 train.py -C fashion:c2f1e:pmsC
tq r5 -- python3 train.py -C fashion:c2f1e:prhomN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-pcontrastN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-ptripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-pmtripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-pstripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-pdtripletN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-pgliftE
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-pnpairE
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-pmarginN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-pquadN
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-pmsC
tq r5 -- python3 swipe.py -v -ppami_mnist -m8 -c logs_fashion-c2f1e-prhomN

tq r5 -- python3 train.py -C cub:res18:pcontrastN
tq r5 -- python3 train.py -C cub:res18:ptripletN
tq r5 -- python3 train.py -C cub:res18:pmtripletN
tq r5 -- python3 train.py -C cub:res18:pstripletN
tq r5 -- python3 train.py -C cub:res18:pdtripletN
tq r5 -- python3 train.py -C cub:res18:pgliftE
tq r5 -- python3 train.py -C cub:res18:pnpairE
tq r5 -- python3 train.py -C cub:res18:pmarginN
tq r5 -- python3 train.py -C cub:res18:pquadN
tq r5 -- python3 train.py -C cub:res18:pmsC
tq r5 -- python3 train.py -C cub:res18:prhomN
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-pcontrastN
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-ptripletN
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-pmtripletN
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-pstripletN
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-pdtripletN
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-pgliftE
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-pnpairE
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-pmarginN
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-pquadN
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-pmsC
tq r5 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18-prhomN

tq r9 -- python3 train.py -C cub:res18d:pcontrastN
tq r9 -- python3 train.py -C cub:res18d:ptripletN
tq r9 -- python3 train.py -C cub:res18d:pmtripletN
tq r9 -- python3 train.py -C cub:res18d:pstripletN
tq r9 -- python3 train.py -C cub:res18d:pdtripletN
tq r9 -- python3 train.py -C cub:res18d:pgliftE
tq r9 -- python3 train.py -C cub:res18d:pnpairE
tq r9 -- python3 train.py -C cub:res18d:pmarginN
tq r9 -- python3 train.py -C cub:res18d:pquadN
tq r9 -- python3 train.py -C cub:res18d:pmsC
tq r9 -- python3 train.py -C cub:res18d:prhomN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-pcontrastN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-ptripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-pmtripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-pstripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-pdtripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-pgliftE
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-pnpairE
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-pmarginN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-pquadN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-pmsC
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18d-prhomN

tq r9 -- python3 train.py -C cub:res18e:pcontrastN
tq r9 -- python3 train.py -C cub:res18e:ptripletN
tq r9 -- python3 train.py -C cub:res18e:pmtripletN
tq r9 -- python3 train.py -C cub:res18e:pstripletN
tq r9 -- python3 train.py -C cub:res18e:pdtripletN
tq r9 -- python3 train.py -C cub:res18e:pgliftE
tq r9 -- python3 train.py -C cub:res18e:pnpairE
tq r9 -- python3 train.py -C cub:res18e:pmarginN
tq r9 -- python3 train.py -C cub:res18e:pquadN
tq r9 -- python3 train.py -C cub:res18e:pmsC
tq r9 -- python3 train.py -C cub:res18e:prhomN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-pcontrastN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-ptripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-pmtripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-pstripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-pdtripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-pgliftE
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-pnpairE
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-pmarginN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-pquadN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-pmsC
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-res18e-prhomN

tq r9 -- python3 train.py -C cub:mnas10:pcontrastN
tq r9 -- python3 train.py -C cub:mnas10:ptripletN
tq r9 -- python3 train.py -C cub:mnas10:pmtripletN
tq r9 -- python3 train.py -C cub:mnas10:pstripletN
tq r9 -- python3 train.py -C cub:mnas10:pdtripletN
tq r9 -- python3 train.py -C cub:mnas10:pgliftE
tq r9 -- python3 train.py -C cub:mnas10:pnpairE
tq r9 -- python3 train.py -C cub:mnas10:pmarginN
tq r9 -- python3 train.py -C cub:mnas10:pquadN
tq r9 -- python3 train.py -C cub:mnas10:pmsC
tq r9 -- python3 train.py -C cub:mnas10:prhomN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-pcontrastN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-ptripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-pmtripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-pstripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-pdtripletN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-pgliftE
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-pnpairE
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-pmarginN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-pquadN
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-pmsC
tq r9 -- python3 swipe.py -v -ppami_imagenet -m8 -c logs_cub-mnas10-prhomN

